export interface NativeBridgeModule {
  initializeRuntime?(appDir: string, customClientConfig: string): string;
  getCoreSnapshot?(server: string): string;
  pullSessionEvents?(): string;
  pullAudioFrames?(): string;
  getLatestVideoFrameMetadata?(sinceFrameId: number): string | null;
  copyLatestVideoFrame?(frameId: number, expectedBytes: number): ArrayBuffer | null;
  getIncomingScreenFrameMetadata?(sinceFrameId: number): string | null;
  copyIncomingScreenFrame?(frameId: number, expectedBytes: number): ArrayBuffer | null;
  updateIncomingScreenFrame?(
    width: number,
    height: number,
    stride: number,
    timestamp: number,
    format: string,
    data: ArrayBuffer | Uint8Array
  ): boolean;
  clearIncomingScreenFrame?(): void;
  refreshSessionVideo?(display: number): boolean;
  harmonyNextRgba?(display: number): void;
  connectToPeer?(peerId: string, password: string, server: string, relayServer: string, apiServer: string): void;
  accountAuth?(op: string, rememberMe: boolean, server: string, relayServer: string, apiServer: string): void;
  accountAuthCancel?(): void;
  accountAuthResult?(): string;
  getLocalOption?(key: string): string;
  getSessionToggleOption?(key: string): boolean;
  setLocalOption?(key: string, value: string): void;
  applySessionOption?(key: string, value: string): boolean;
  closeSession?(): void;
  reconnectSession?(forceRelay: boolean): boolean;
  restartRemoteDevice?(): boolean;
  lockRemoteScreen?(): boolean;
  submitSessionPassword?(password: string, remember: boolean): boolean;
  setIncomingServiceEnabled?(enabled: boolean, server: string, relayServer: string, apiServer: string): string;
  bootstrapCoreSnapshot?(displayId: string, fingerprint: string, directAddress: string, server: string): string;
  sendMouseInput?(mask: number, x: number, y: number): boolean;
  sendKeyboardInput?(keyCode: number, isPressed: boolean, modifiers: number): boolean;
  sendCtrlAltDel?(): boolean;
  sendClipboardData?(content: string, timestamp: number): boolean;
  sendVideoFrameMetadata?(
    codec: number,
    width: number,
    height: number,
    timestamp: number,
    keyFrame: boolean,
    dataLength: number
  ): boolean;
  sendAudioFrameMetadata?(
    codec: number,
    sampleRate: number,
    channels: number,
    timestamp: number,
    dataLength: number
  ): boolean;
  startNativeScreenCapture?(width: number, height: number, frameRate: number): boolean;
  stopNativeScreenCapture?(): boolean;
  isNativeScreenCaptureActive?(): boolean;
  getNativeScreenCaptureStats?(): string;
  requestInputInjectionAuthorization?(): number;
  getInputInjectionAuthorizationStatus?(): number;
  cancelInputInjectionAuthorization?(): void;
  setInputInjectionEnabled?(enabled: boolean): boolean;
  sendChatMessage?(peerId: string, messageType: string, content: string, timestamp: number): boolean;
  sendFileTransferRequest?(
    taskId: string,
    peerId: string,
    fileName: string,
    totalBytes: number,
    direction: string
  ): boolean;
  openTerminal?(terminalId: number, rows: number, cols: number): boolean;
  sendTerminalInput?(terminalId: number, data: string): boolean;
  resizeTerminal?(terminalId: number, rows: number, cols: number): boolean;
  closeTerminal?(terminalId: number): boolean;
  readRemoteDirectory?(path: string, includeHidden: boolean): boolean;
  createRemoteDirectory?(path: string): boolean;
  deleteRemotePath?(path: string, isDirectory: boolean): boolean;
  startFileTransfer?(path: string, to: string, isRemote: boolean): boolean;
  queryOnlines?(idsJson: string): boolean;
  discoverLanPeers?(): void;
  loadLanPeers?(): string;
  removeDiscoveredPeer?(peerId: string): boolean;

  getSessionStage(): string;
  getActivePeerId(): string;
  getConnectStatusSummary(): string;
  getConnectDetailMessage(): string;
  getConnectLastError(): string;
  drainConnectEventsJson(): string;
  getCoreSnapshotJson(server: string): string;
  initializeRuntime(app_dir: string, custom_client_config: string): string;
  pullSessionEventsJson(): string;
  pullAudioFramesJson(): string;
  getLatestVideoFrameMetadataJson(since_frame_id: number): string;
  getIncomingScreenFrameMetadataJson(since_frame_id: number): string;
  copyIncomingScreenFrame(frame_id: number, expected_bytes: number): ArrayBuffer | null;
  updateIncomingScreenFrame(
    width: number,
    height: number,
    stride: number,
    timestamp: number,
    format: string,
    data: ArrayBuffer | Uint8Array
  ): boolean;
  clearIncomingScreenFrame(): void;
  copyLatestVideoFrame(frame_id: number, buffer: any): number;
  refreshSessionVideo(display: number): boolean;
  harmonyNextRgba(display: number): void;
  mainStartService(enabled: boolean, server: string, relay_server: string, api_server: string): string;
  bootstrapCoreSnapshot(display_id: string, fingerprint: string, direct_address: string, server: string): string;
  sessionSendMouse(mask: number, x: number, y: number): boolean;
  sessionInputKey(key_code: number, is_pressed: boolean, modifiers: number): boolean;
  sessionCtrlAltDel(): boolean;
  sendClipboardData(content: string, timestamp: number): boolean;
  sendVideoFrameMetadata(codec: number, width: number, height: number, timestamp: number, key_frame: boolean, data_length: number): boolean;
  sendAudioFrameMetadata(codec: number, sample_rate: number, channels: number, timestamp: number, data_length: number): boolean;
  startNativeScreenCapture(width: number, height: number, frameRate: number): boolean;
  stopNativeScreenCapture(): boolean;
  isNativeScreenCaptureActive(): boolean;
  getNativeScreenCaptureStats(): string;
  requestInputInjectionAuthorization(): number;
  getInputInjectionAuthorizationStatus(): number;
  cancelInputInjectionAuthorization(): void;
  setInputInjectionEnabled(enabled: boolean): boolean;
  sessionSendChat(peerId: string, messageType: string, content: string, timestamp: number): boolean;
  sendFileTransferRequest(task_id: string, file_name: string, total_bytes: number, direction: string): boolean;
  sessionStart(peer_id: string, password: string, server: string, relay_server: string, api_server: string): void;
  mainAccountAuth(op: string, remember_me: boolean, server: string, relay_server: string, api_server: string): void;
  mainAccountAuthCancel(): void;
  mainAccountAuthResult(): string;
  mainGetLocalOption(key: string): string;
  mainGetPeerOption(peer_id: string, key: string): string;
  getPeerInfo(peer_id: string): string;
  sessionGetToggleOption(key: string): boolean;
  mainSetLocalOption(key: string, value: string): void;
  applySessionOption(key: string, value: string): boolean;
  markSessionConnected(peer_id: string): void;
  sessionReconnect(force_relay: boolean): boolean;
  markSessionError(message: string): void;
  sessionClose(): void;
  sessionLogin(password: string, remember: boolean): boolean;
  sessionRestartRemoteDevice(): boolean;
  sessionLockScreen(): boolean;
  sessionOpenTerminal(terminal_id: number, rows: number, cols: number): boolean;
  sessionSendTerminalInput(terminal_id: number, data: string): boolean;
  sessionResizeTerminal(terminal_id: number, rows: number, cols: number): boolean;
  sessionCloseTerminal(terminal_id: number): boolean;
  sessionReadRemoteDir(path: string, include_hidden: boolean): boolean;
  sessionCreateDir(path: string): boolean;
  deleteRemotePath(path: string, is_directory: boolean): boolean;
  sessionSendFiles(path: string, to: string, is_remote: boolean): boolean;
  queryOnlines(ids_json: string): boolean;
  mainDiscover(): void;
  mainLoadLanPeers(): string;
  mainRemoveDiscovered(peer_id: string): boolean;
  sessionSend2fa(code: string, trust_this_device: boolean): boolean;
  sessionToggleOption(name: string): void;
  sessionTogglePrivacyMode(impl_key: string, on: boolean): boolean;
  sessionSwitchDisplay(display: number): boolean;
  sessionEnterOrLeave(): boolean;
  sessionLeave(): boolean;
  sessionSetSize(display: number, width: number, height: number): void;
  sessionChangeResolution(display: number, width: number, height: number): void;
  sessionElevateDirect(): void;
  sessionElevateWithLogon(username: string, password: string): void;
  sessionSwitchSides(): boolean;
  sessionTakeScreenshot(display: number): boolean;
  sessionRecordScreen(start: boolean): boolean;
  sessionGetIsRecording(): boolean;
  sessionRequestVoiceCall(): boolean;
  sessionCloseVoiceCall(): boolean;
  sessionAddPortForward(local_port: number, remote_host: string, remote_port: number): void;
  sessionRemovePortForward(local_port: number): void;
  sessionNewRdp(): void;
  sessionRemoveFile(act_id: number, path: string, file_num: number, is_remote: boolean): void;
  sessionRenameFile(act_id: number, path: string, new_name: string, is_remote: boolean): void;
  sessionCancelJob(act_id: number): void;
  sessionResumeJob(act_id: number, is_remote: boolean): void;
  sessionSetConfirmOverrideFile(act_id: number, file_num: number, need_override: boolean, remember: boolean, is_upload: boolean): void;
  sessionSendNote(note: string): void;
  sessionInputString(value: string): void;
  sessionInputOsPassword(pass: string): void;
  sessionLoadLastTransferJobs(): void;
  sessionGetViewStyle(): string;
  sessionSetViewStyle(value: string): void;
  sessionGetScrollStyle(): string;
  sessionSetScrollStyle(value: string): void;
  sessionGetImageQuality(): string;
  sessionSetImageQuality(value: string): void;
  sessionGetKeyboardMode(): string;
  sessionSetKeyboardMode(value: string): void;
  sessionGetCustomImageQuality(): string;
  sessionSetCustomImageQuality(value: number): void;
  sessionSetCustomFps(fps: number): void;
  sessionGetTrackpadSpeed(): number;
  sessionSetTrackpadSpeed(value: number): void;
  sessionGetFlutterOption(k: string): string;
  sessionSetFlutterOption(k: string, v: string): void;
  sessionGetReverseMouseWheelSync(): string;
  sessionSetReverseMouseWheel(value: string): void;
  sessionGetOption(k: string): string;
  sessionSetOption(k: string, v: string): void;
  sessionGetPeerOption(name: string): string;
  sessionPeerOption(name: string, value: string): void;
  sessionIsKeyboardModeSupported(mode: string): boolean;
  sessionGetPlatform(is_remote: boolean): string;
  sessionGetRemember(): boolean;
  sessionGetEnableTrustedDevices(): boolean;
  sessionGetAlternativeCodecs(): string;
  sessionChangePreferCodec(): void;
  mainGetOption(key: string): string;
  mainSetOption(key: string, value: string): void;
  mainGetOptions(): string;
  mainGetMyId(): string;
  mainGetUuid(): string;
  mainGetVersion(): string;
  mainGetFingerprint(): string;
  mainGetApiServer(): string;
  mainGetTemporaryPassword(): string;
  mainSetPermanentPasswordWithResult(password: string): boolean;
  mainUpdateTemporaryPassword(): void;
  mainTestIfValidServer(server: string): string;
  mainGetConnectStatus(): string;
  mainIsUsingPublicServer(): boolean;
  mainForgetPassword(id: string): void;
  mainPeerHasPassword(id: string): boolean;
  mainPeerExists(id: string): boolean;
  mainSetPeerAlias(id: string, alias: string): void;
  mainSetPeerOption(id: string, key: string, value: string): void;
  mainRemovePeer(id: string): void;
  mainGetNewStoredPeers(): string;
  mainLoadRecentPeers(): void;
  mainGetLangs(): string;
  mainGetError(): string;
  mainGetBuildDate(): string;
  mainGetLicense(): string;
  mainGetAppName(): string;
  mainHasHwcodec(): boolean;
  mainGenerate2fa(): string;
  mainVerify2fa(code: string): boolean;
  mainGetTrustedDevices(): string;
  mainClearTrustedDevices(): void;
  mainSetUserDefaultOption(key: string, value: string): void;
  mainGetUserDefaultOption(key: string): string;
  mainResolveAvatarUrl(avatar: string): string;
  mainGetLoginDeviceInfo(): string;
  mainGetHardOption(key: string): string;
  mainGetBuildinOption(key: string): string;
  mainGetCommon(key: string): string;
  mainSetCommon(key: string, value: string): void;
  mainCheckConnectStatus(): void;
  mainStopService(): void;
  mainOnMainWindowClose(): void;
  mainWol(id: string): void;
  mainHttpRequest(url: string, method: string, body: string, header: string): void;
  sessionIsFileTransfer(): boolean;
  sessionIsTerminal(): boolean;
  sessionIsPortForward(): boolean;
  sessionIsRdp(): boolean;
  sessionIsViewCamera(): boolean;
  sessionToggleVirtualDisplay(index: number, on: boolean): void;
  sessionGetAuditServer(typ: string): string;
  sessionSendSelectedSessionId(sid: string): void;
  sessionGetConnToken(): string;
  sessionHandleFlutterKeyEvent(keyboard_mode: string, character: string, usb_hid: number, lock_modes: number, down_or_up: boolean): void;
  sessionHandleFlutterRawKeyEvent(keyboard_mode: string, name: string, platform_code: number, position_code: number, lock_modes: number, down_or_up: boolean): void;
  sessionSendTouchScale(scale: number, alt: boolean, ctrl: boolean, shift: boolean, command: boolean): void;
  sessionSendTouchPanEvent(event: string, x: number, y: number, alt: boolean, ctrl: boolean, shift: boolean, command: boolean): void;
  sessionRefresh(): void;
  sessionGetPeerVersion(): string;
  sessionGetPathSep(): string;
  sessionIsRestartingRemoteDevice(): boolean;
  cmInit(): void;
  cmGetClientsState(): string;
  cmCheckClientsLength(length: number): string;
  cmGetClientsLength(): any;
  cmSendChat(conn_id: number, msg: string): void;
  cmLoginRes(conn_id: number, res: boolean): void;
  cmCloseConnection(conn_id: number): void;
  cmRemoveDisconnectedConnection(conn_id: number): void;
  cmCheckClickTime(conn_id: number): void;
  cmGetClickTime(): any;
  cmSwitchPermission(conn_id: number, name: string, enabled: boolean): void;
  cmCanElevate(): boolean;
  cmElevatePortable(conn_id: number): void;
  cmSwitchBack(conn_id: number): void;
  cmGetConfig(name: string): string;
  cmHandleIncomingVoiceCall(id: number, accept: boolean): void;
  cmCloseVoiceCall(id: number): void;
  pluginEvent(id: string, peer: string, msg: string): void;
  pluginRegisterEventStream(id: string, peer: string): void;
  pluginGetSessionOption(id: string, key: string): string;
  pluginSetSessionOption(id: string, key: string, value: string): void;
  pluginGetSharedOption(id: string, key: string): string;
  pluginSetSharedOption(id: string, key: string, value: string): void;
  pluginReload(id: string): void;
  pluginEnable(id: string, enable: boolean): void;
  pluginIsEnabled(id: string): boolean;
  pluginFeatureIsEnabled(id: string): boolean;
  pluginSyncUi(id: string): void;
  pluginListReload(): void;
  pluginInstall(id: string, b: boolean): void;
  installInstallMe(path: string, options: string, exe: string): void;
  installInstallOptions(): string;
  installInstallPath(): string;
  installRunWithoutInstall(): boolean;
  installShowRunWithoutInstall(): boolean;
  isCustomClient(): boolean;
  isDisableAb(): boolean;
  isDisableAccount(): boolean;
  isDisableGroupPanel(): boolean;
  isDisableInstallation(): boolean;
  isDisableSettings(): boolean;
  isIncomingOnly(): boolean;
  isOutgoingOnly(): boolean;
  isPresetPassword(): boolean;
  isPresetPasswordMobileOnly(): boolean;
  isSelinuxEnforcing(): boolean;
  isSupportMultiUiSession(): boolean;
  mainChangeId(id: string): void;
  mainChangeLanguage(lang: string): void;
  mainChangeTheme(dark: string): void;
  mainGetDisplays(): string;
  mainGetPrinterNames(): string;
  mainGetSocks(): string;
  mainSetSocks(proxy: string, username: string, password: string): void;
  mainGetProxyStatus(): boolean;
  mainGetAppNameSync(): string;
  mainGetNewVersion(): string;
  mainGetHomeDir(): string;
  mainDeviceId(): string;
  mainDeviceName(): string;
  mainIsInstalled(): boolean;
  mainIsInstalledDaemon(): boolean;
  mainIsRoot(): boolean;
  mainIsProcessTrusted(): boolean;
  mainIsCanScreenRecording(): boolean;
  mainIsCanInputMonitoring(): boolean;
  mainCurrentIsWayland(): boolean;
  mainIsLoginWayland(): boolean;
  mainHasVram(): boolean;
  mainSupportedHwdecodings(): string;
  mainCheckHwcodec(): void;
  mainCreateShortcut(): boolean;
  mainGetMouseTime(): any;
  mainCheckMouseTime(): boolean;
  mainGetAsyncStatus(): string;
  mainGetLanPeers(): string;
  mainGetLastRemoteId(): string;
  mainGetFav(): string;
  mainStoreFav(fav: string): void;
  mainGetPeerSync(id: string): string;
  mainGetPeerFlutterOptionSync(id: string, k: string): string;
  mainSetPeerFlutterOptionSync(id: string, k: string, v: string): void;
  mainGetPeerOptionSync(id: string, k: string): string;
  mainSetPeerOptionSync(id: string, k: string, v: string): void;
  mainRemoveTrustedDevices(json: string): void;
  mainHasValid_2faSync(): boolean;
  mainHasValidBotSync(): boolean;
  mainVerifyBot(token: string): boolean;
  mainMaxEncryptLen(): any;
  mainGetUnlockPin(): string;
  mainSetUnlockPin(pin: string): void;
  mainOptionSynced(): boolean;
  mainSupportRemoveWallpaper(): boolean;
  mainTestWallpaper(): boolean;
  mainSupportedPrivacyModeImpls(): string;
  mainDefaultPrivacyModeImpl(): string;
  mainIsOptionFixed(key: string): boolean;
  mainGetUseTextureRender(): boolean;
  mainHasFileClipboard(): boolean;
  mainHasGpuTextureRender(): boolean;
  mainAudioSupportLoopback(): boolean;
  mainIsShareRdp(): boolean;
  mainSetShareRdp(v: boolean): void;
  mainIsInstalledLowerVersion(): boolean;
  mainGetSoftwareUpdateUrl(): string;
  mainHandleRelayId(id: string): void;
  mainHideDock(): void;
  mainSetCursorPosition(x: number, y: number): void;
  mainClipCursor(): void;
  mainGetEnv(key: string): string;
  mainSetEnv(key: string, value: string): void;
  mainSetHomeDir(home: string): void;
  mainStartDbusServer(): void;
  mainStartIpcUrlServer(): void;
  mainCheckSuperUserPermission(): boolean;
  mainGotoInstall(): string;
  mainUpdateMe(path: string): void;
  mainDeployDevice(): boolean;
  mainGetMainDisplay(): string;
  mainGetInputSource(): string;
  mainSetInputSource(source: string): void;
  mainInitInputSource(): void;
  mainSupportedInputSource(): string;
  mainVideoSaveDirectory(): string;
  mainGetDataDirIos(): string;
  mainShowOption(key: string): boolean;
  mainSetOptions(options: string): void;
  mainGetOptionsSync(): string;
  mainGetOptionSync(key: string): string;
  mainGetCommonSync(key: string): string;
  mainGetHttpStatus(): string;
  mainUriPrefixSync(): string;
  mainLoadAb(): string;
  mainSaveAb(ab: string): void;
  mainClearAb(): void;
  mainLoadGroup(): string;
  mainSaveGroup(group: string): void;
  mainClearGroup(): void;
  mainLoadFavPeers(): string;
  mainLoadRecentPeersForAb(): string;
  mainHandleWaylandScreencastRestoreToken(token: string): void;
  getDoubleClickTime(): any;
  getLocalFlutterOption(k: string): string;
  setLocalFlutterOption(k: string, v: string): void;
  getLocalKbLayoutType(): string;
  setLocalKbLayoutType(v: string): void;
  getVoiceCallInputDevice(): string;
  setVoiceCallInputDevice(device: string): void;
  hostStopSystemKeyPropagate(stop: boolean): void;
  optionSynced(): boolean;
  peerGetSessionsCount(): any;
  sendUrlScheme(url: string): void;
  setCurSessionId(id: string): void;
  startGlobalEventStream(): void;
  stopGlobalEventStream(): void;
  translate(name: string): string;
  versionToNumber(v: string): any;
  willSessionCloseCloseSession(): boolean;
  getNextTextureKey(): number;

  mainInit(app_dir: any, custom_client_config: any): void;
  sessionAddExistedSync(is_sync: boolean): boolean;
  sessionAddJob(id: number, path: any, to: any, file_num: number, include_hidden: boolean, is_remote: boolean): void;
  sessionAddSync(is_sync: boolean): void;
  sessionGetAuditGuid(): string;
  sessionGetAuditServerSync(typ: any): string;
  sessionGetCommon(key: any): string;
  sessionGetCommonSync(key: any): string;
  sessionGetConnSessionId(): string;
  sessionGetDisplaysAsIndividualWindows(): string;
  sessionGetEdgeScrollEdgeThickness(): number;
  sessionGetLastAuditNote(): string;
  sessionGetRgbaSize(display: number): number;
  sessionGetToggleOptionSync(arg: any): boolean;
  sessionGetUseAllMyDisplaysForTheRemoteSession(): string;
  sessionHandleScreenshot(action: any): string;
  sessionIsMultiUiSession(): boolean;
  sessionNextRgba(display: number): void;
  sessionOnWaitingForImageDialogShow(): void;
  sessionPrinterResponse(id: number, path: any, printer_name: any): void;
  sessionReadDirToRemoveRecursive(id: number, path: any, include_hidden: boolean): void;
  sessionReadLocalDirSync(path: any, include_hidden: boolean, id: number): string;
  sessionReadLocalEmptyDirsRecursiveSync(id: number, path: any): string;
  sessionReadRemoteEmptyDirsRecursiveSync(id: number, path: any): string;
  sessionRegisterGpuTexture(display: number): number;
  sessionRegisterPixelbufferTexture(display: number): number;
  sessionRemoveAllEmptyDirs(id: number): void;
  sessionRequestNewDisplayInitMsgs(display: number): void;
  sessionSendPointer(msg: any): void;
  sessionSetAuditGuid(guid: any): void;
  sessionSetDisplaysAsIndividualWindows(value: any): void;
  sessionSetEdgeScrollEdgeThickness(value: number): void;
  sessionSetUseAllMyDisplaysForTheRemoteSession(value: any): void;
  sessionStartWithDisplays(displays: any): boolean;
}

declare const rustdeskBridgeLibrary: NativeBridgeModule;
export default rustdeskBridgeLibrary;
