export class CoreBuildInfo {
  static readonly FILE_NAME: string = "librustdesk_core.a";
  static readonly SOURCE_PATH: string = "entry/src/main/libs/arm64/librustdesk_core.a";
  static readonly FILE_SIZE: string = "132777178";
  static readonly FILE_SIZE_MB: string = "126.63";
  static readonly MODIFIED_TIME: string = "1781914606";
  static readonly COMPILE_TIME: string = "2026-06-20 08:16";
  static readonly HASH_FNV1A_1MB: string = "93d83a9e";
  static readonly HASH_SHA256: string = "EE881BEB9DE44835EE126BACC86D3B373E779334FB58A5D63F4B4D7974077314";
  static readonly X86_64_FILE_SIZE: string = "130416964";
  static readonly X86_64_MODIFIED_TIME: string = "1781914885";
  static readonly X86_64_COMPILE_TIME: string = "2026-06-20 08:21";
  static readonly X86_64_HASH_FNV1A_1MB: string = "ff94d136";
  static readonly X86_64_HASH_SHA256: string = "8ACD4AD130EAE9A36D4AE04A93860193CE8773E91E5CCEA5E34E815BFE633ED4";
  static readonly COMPATIBLE_OFFICIAL_VERSION: string = "";
  static readonly GENERATED_AT: string = "2026-06-24 18:36";
}
