export class CoreBuildInfo {
  static readonly FILE_NAME: string = "librustdesk_core.a";
  static readonly SOURCE_PATH: string = "entry/src/main/libs/arm64/librustdesk_core.a";
  static readonly FILE_SIZE: string = "133417396";
  static readonly FILE_SIZE_MB: string = "127.24";
  static readonly MODIFIED_TIME: string = "1788256559";
  static readonly COMPILE_TIME: string = "2026-09-01 17:55";
  static readonly HASH_FNV1A_1MB: string = "7d56d46b";
  static readonly HASH_SHA256: string = "25CC4C517C92D6AA79B82B2895796A597ADF14361396137002BB46C2EBD895BD";
  static readonly X86_64_FILE_SIZE: string = "130750894";
  static readonly X86_64_MODIFIED_TIME: string = "1788256710";
  static readonly X86_64_COMPILE_TIME: string = "2026-09-01 17:58";
  static readonly X86_64_HASH_FNV1A_1MB: string = "d80c2cbc";
  static readonly X86_64_HASH_SHA256: string = "3BC91357DC3051EF398828FDC834E2CB935B8C05AA00905BDC736962B5183F99";
  static readonly COMPATIBLE_OFFICIAL_VERSION: string = "1.4.6";
  static readonly GENERATED_AT: string = "2026-09-02 08:59";
}
