export class CoreBuildInfo {
  static readonly FILE_NAME: string = "librustdesk_core.a";
  static readonly SOURCE_PATH: string = "entry/src/main/libs/arm64/librustdesk_core.a";
  static readonly FILE_SIZE: string = "133353216";
  static readonly FILE_SIZE_MB: string = "127.18";
  static readonly MODIFIED_TIME: string = "1787015682";
  static readonly COMPILE_TIME: string = "2026-08-18 09:14";
  static readonly HASH_FNV1A_1MB: string = "7752e95d";
  static readonly HASH_SHA256: string = "AE629ED2045851469952DAF881D86E963C5344C787745AA5DDB69387EBBA41B5";
  static readonly X86_64_FILE_SIZE: string = "130840066";
  static readonly X86_64_MODIFIED_TIME: string = "1787016930";
  static readonly X86_64_COMPILE_TIME: string = "2026-08-18 09:35";
  static readonly X86_64_HASH_FNV1A_1MB: string = "04cb3121";
  static readonly X86_64_HASH_SHA256: string = "2199D151CD6C2900BD1FB489561F6C7716314147DF2F87F542178134C4482476";
  static readonly COMPATIBLE_OFFICIAL_VERSION: string = "1.4.6";
  static readonly GENERATED_AT: string = "2026-08-18 17:54";
}
